// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi.Domains
{
    [GandiResourceType("gandi:domains/domain:Domain")]
    public partial class Domain : global::Pulumi.CustomResource
    {
        [Output("admin")]
        public Output<Outputs.DomainAdmin> Admin { get; private set; } = null!;

        /// <summary>
        /// Should the domain autorenew
        /// </summary>
        [Output("autorenew")]
        public Output<bool?> Autorenew { get; private set; } = null!;

        [Output("billing")]
        public Output<Outputs.DomainBilling> Billing { get; private set; } = null!;

        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        [Output("nameservers")]
        public Output<ImmutableArray<string>> Nameservers { get; private set; } = null!;

        [Output("owner")]
        public Output<Outputs.DomainOwner> Owner { get; private set; } = null!;

        /// <summary>
        /// A list of tags attached to the domain
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        [Output("tech")]
        public Output<Outputs.DomainTech> Tech { get; private set; } = null!;


        /// <summary>
        /// Create a Domain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Domain(string name, DomainArgs args, CustomResourceOptions? options = null)
            : base("gandi:domains/domain:Domain", name, args ?? new DomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Domain(string name, Input<string> id, DomainState? state = null, CustomResourceOptions? options = null)
            : base("gandi:domains/domain:Domain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Domain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Domain Get(string name, Input<string> id, DomainState? state = null, CustomResourceOptions? options = null)
        {
            return new Domain(name, id, state, options);
        }
    }

    public sealed class DomainArgs : global::Pulumi.ResourceArgs
    {
        [Input("admin")]
        public Input<Inputs.DomainAdminArgs>? Admin { get; set; }

        /// <summary>
        /// Should the domain autorenew
        /// </summary>
        [Input("autorenew")]
        public Input<bool>? Autorenew { get; set; }

        [Input("billing")]
        public Input<Inputs.DomainBillingArgs>? Billing { get; set; }

        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        [Obsolete(@"This nameservers attribute will be removed on next major release: the nameservers resource has to be used instead.
See https://github.com/go-gandi/terraform-provider-gandi/issues/88 for details.")]
        public InputList<string> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        [Input("owner", required: true)]
        public Input<Inputs.DomainOwnerArgs> Owner { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags attached to the domain
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tech")]
        public Input<Inputs.DomainTechArgs>? Tech { get; set; }

        public DomainArgs()
        {
        }
        public static new DomainArgs Empty => new DomainArgs();
    }

    public sealed class DomainState : global::Pulumi.ResourceArgs
    {
        [Input("admin")]
        public Input<Inputs.DomainAdminGetArgs>? Admin { get; set; }

        /// <summary>
        /// Should the domain autorenew
        /// </summary>
        [Input("autorenew")]
        public Input<bool>? Autorenew { get; set; }

        [Input("billing")]
        public Input<Inputs.DomainBillingGetArgs>? Billing { get; set; }

        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        [Obsolete(@"This nameservers attribute will be removed on next major release: the nameservers resource has to be used instead.
See https://github.com/go-gandi/terraform-provider-gandi/issues/88 for details.")]
        public InputList<string> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        [Input("owner")]
        public Input<Inputs.DomainOwnerGetArgs>? Owner { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A list of tags attached to the domain
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tech")]
        public Input<Inputs.DomainTechGetArgs>? Tech { get; set; }

        public DomainState()
        {
        }
        public static new DomainState Empty => new DomainState();
    }
}
