// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi.Domains
{
    [GandiResourceType("gandi:domains/nameservers:Nameservers")]
    public partial class Nameservers : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        [Output("nameservers")]
        public Output<ImmutableArray<string>> Servers { get; private set; } = null!;


        /// <summary>
        /// Create a Nameservers resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Nameservers(string name, NameserversArgs args, CustomResourceOptions? options = null)
            : base("gandi:domains/nameservers:Nameservers", name, args ?? new NameserversArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Nameservers(string name, Input<string> id, NameserversState? state = null, CustomResourceOptions? options = null)
            : base("gandi:domains/nameservers:Nameservers", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Nameservers resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Nameservers Get(string name, Input<string> id, NameserversState? state = null, CustomResourceOptions? options = null)
        {
            return new Nameservers(name, id, state, options);
        }
    }

    public sealed class NameserversArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        public InputList<string> Servers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        public NameserversArgs()
        {
        }
        public static new NameserversArgs Empty => new NameserversArgs();
    }

    public sealed class NameserversState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The FQDN of the domain
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        [Input("nameservers")]
        private InputList<string>? _nameservers;

        /// <summary>
        /// A list of nameservers for the domain
        /// </summary>
        public InputList<string> Servers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        public NameserversState()
        {
        }
        public static new NameserversState Empty => new NameserversState();
    }
}
