# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_gandi.config as __config
    config = __config
    import pulumiverse_gandi.domains as __domains
    domains = __domains
    import pulumiverse_gandi.email as __email
    email = __email
    import pulumiverse_gandi.livedns as __livedns
    livedns = __livedns
    import pulumiverse_gandi.simplehosting as __simplehosting
    simplehosting = __simplehosting
else:
    config = _utilities.lazy_import('pulumiverse_gandi.config')
    domains = _utilities.lazy_import('pulumiverse_gandi.domains')
    email = _utilities.lazy_import('pulumiverse_gandi.email')
    livedns = _utilities.lazy_import('pulumiverse_gandi.livedns')
    simplehosting = _utilities.lazy_import('pulumiverse_gandi.simplehosting')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gandi",
  "mod": "domains/dNSSecKey",
  "fqn": "pulumiverse_gandi.domains",
  "classes": {
   "gandi:domains/dNSSecKey:DNSSecKey": "DNSSecKey"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/domain",
  "fqn": "pulumiverse_gandi.domains",
  "classes": {
   "gandi:domains/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/glueRecord",
  "fqn": "pulumiverse_gandi.domains",
  "classes": {
   "gandi:domains/glueRecord:GlueRecord": "GlueRecord"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/nameservers",
  "fqn": "pulumiverse_gandi.domains",
  "classes": {
   "gandi:domains/nameservers:Nameservers": "Nameservers"
  }
 },
 {
  "pkg": "gandi",
  "mod": "email/forwarding",
  "fqn": "pulumiverse_gandi.email",
  "classes": {
   "gandi:email/forwarding:Forwarding": "Forwarding"
  }
 },
 {
  "pkg": "gandi",
  "mod": "email/mailbox",
  "fqn": "pulumiverse_gandi.email",
  "classes": {
   "gandi:email/mailbox:Mailbox": "Mailbox"
  }
 },
 {
  "pkg": "gandi",
  "mod": "livedns/domain",
  "fqn": "pulumiverse_gandi.livedns",
  "classes": {
   "gandi:livedns/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "livedns/record",
  "fqn": "pulumiverse_gandi.livedns",
  "classes": {
   "gandi:livedns/record:Record": "Record"
  }
 },
 {
  "pkg": "gandi",
  "mod": "simplehosting/instance",
  "fqn": "pulumiverse_gandi.simplehosting",
  "classes": {
   "gandi:simplehosting/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "gandi",
  "mod": "simplehosting/vHost",
  "fqn": "pulumiverse_gandi.simplehosting",
  "classes": {
   "gandi:simplehosting/vHost:VHost": "VHost"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gandi",
  "token": "pulumi:providers:gandi",
  "fqn": "pulumiverse_gandi",
  "class": "Provider"
 }
]
"""
)
