// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.simplehosting.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class InstanceState extends com.pulumi.resources.ResourceArgs {

    public static final InstanceState Empty = new InstanceState();

    /**
     * The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
     * 
     */
    @Import(name="databaseName")
    private @Nullable Output<String> databaseName;

    /**
     * @return The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
     * 
     */
    public Optional<Output<String>> databaseName() {
        return Optional.ofNullable(this.databaseName);
    }

    /**
     * The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
     * 
     */
    @Import(name="languageName")
    private @Nullable Output<String> languageName;

    /**
     * @return The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
     * 
     */
    public Optional<Output<String>> languageName() {
        return Optional.ofNullable(this.languageName);
    }

    /**
     * The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
     * 
     */
    @Import(name="location")
    private @Nullable Output<String> location;

    /**
     * @return The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
     * 
     */
    public Optional<Output<String>> location() {
        return Optional.ofNullable(this.location);
    }

    /**
     * The name of the SimpleHosting instance
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the SimpleHosting instance
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
     * 
     */
    @Import(name="size")
    private @Nullable Output<String> size;

    /**
     * @return The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
     * 
     */
    public Optional<Output<String>> size() {
        return Optional.ofNullable(this.size);
    }

    private InstanceState() {}

    private InstanceState(InstanceState $) {
        this.databaseName = $.databaseName;
        this.languageName = $.languageName;
        this.location = $.location;
        this.name = $.name;
        this.size = $.size;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(InstanceState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private InstanceState $;

        public Builder() {
            $ = new InstanceState();
        }

        public Builder(InstanceState defaults) {
            $ = new InstanceState(Objects.requireNonNull(defaults));
        }

        /**
         * @param databaseName The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
         * 
         * @return builder
         * 
         */
        public Builder databaseName(@Nullable Output<String> databaseName) {
            $.databaseName = databaseName;
            return this;
        }

        /**
         * @param databaseName The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
         * 
         * @return builder
         * 
         */
        public Builder databaseName(String databaseName) {
            return databaseName(Output.of(databaseName));
        }

        /**
         * @param languageName The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
         * 
         * @return builder
         * 
         */
        public Builder languageName(@Nullable Output<String> languageName) {
            $.languageName = languageName;
            return this;
        }

        /**
         * @param languageName The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
         * 
         * @return builder
         * 
         */
        public Builder languageName(String languageName) {
            return languageName(Output.of(languageName));
        }

        /**
         * @param location The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
         * 
         * @return builder
         * 
         */
        public Builder location(@Nullable Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param name The name of the SimpleHosting instance
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the SimpleHosting instance
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param size The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
         * 
         * @return builder
         * 
         */
        public Builder size(@Nullable Output<String> size) {
            $.size = size;
            return this;
        }

        /**
         * @param size The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
         * 
         * @return builder
         * 
         */
        public Builder size(String size) {
            return size(Output.of(size));
        }

        public InstanceState build() {
            return $;
        }
    }

}
