provider: gandi
template: external-bridged-provider
organization: pulumiverse
providerDefaultBranch: main
upstreamProviderOrg: gandi
pulumiConvert: 1
publish:
    cdn: false
registryDocs: true
publishRegistry: false
goBuildParallelism: 2
autoMergeProviderUpgrades: true
