provider: gandi
template: external-bridged-provider
organization: pulumiverse
providerDefaultBranch: main
upstreamProviderOrg: gandi
pulumiConvert: 1
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
registryDocs: true
publishRegistry: false
goBuildParallelism: 2
autoMergeProviderUpgrades: true