// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { InstanceArgs, InstanceState } from "./instance";
export type Instance = import("./instance").Instance;
export const Instance: typeof import("./instance").Instance = null as any;
utilities.lazyLoad(exports, ["Instance"], () => require("./instance"));

export { VHostArgs, VHostState } from "./vhost";
export type VHost = import("./vhost").VHost;
export const VHost: typeof import("./vhost").VHost = null as any;
utilities.lazyLoad(exports, ["VHost"], () => require("./vhost"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "gandi:simplehosting/instance:Instance":
                return new Instance(name, <any>undefined, { urn })
            case "gandi:simplehosting/vHost:VHost":
                return new VHost(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("gandi", "simplehosting/instance", _module)
pulumi.runtime.registerResourceModule("gandi", "simplehosting/vHost", _module)
