// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.domains.DNSSecKeyArgs;
import com.pulumi.gandi.domains.inputs.DNSSecKeyState;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="gandi:domains/dNSSecKey:DNSSecKey")
public class DNSSecKey extends com.pulumi.resources.CustomResource {
    /**
     * DNSSEC algorithm type
     * 
     */
    @Export(name="algorithm", refs={Integer.class}, tree="[0]")
    private Output<Integer> algorithm;

    /**
     * @return DNSSEC algorithm type
     * 
     */
    public Output<Integer> algorithm() {
        return this.algorithm;
    }
    /**
     * Domain name
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    /**
     * @return Domain name
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }
    /**
     * DNSSEC public key
     * 
     */
    @Export(name="publicKey", refs={String.class}, tree="[0]")
    private Output<String> publicKey;

    /**
     * @return DNSSEC public key
     * 
     */
    public Output<String> publicKey() {
        return this.publicKey;
    }
    /**
     * DNSSEC key type
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return DNSSEC key type
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DNSSecKey(java.lang.String name) {
        this(name, DNSSecKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DNSSecKey(java.lang.String name, DNSSecKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DNSSecKey(java.lang.String name, DNSSecKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:domains/dNSSecKey:DNSSecKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DNSSecKey(java.lang.String name, Output<java.lang.String> id, @Nullable DNSSecKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:domains/dNSSecKey:DNSSecKey", name, state, makeResourceOptions(options, id), false);
    }

    private static DNSSecKeyArgs makeArgs(DNSSecKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DNSSecKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DNSSecKey get(java.lang.String name, Output<java.lang.String> id, @Nullable DNSSecKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DNSSecKey(name, id, state, options);
    }
}
