// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.domains.DomainArgs;
import com.pulumi.gandi.domains.inputs.DomainState;
import com.pulumi.gandi.domains.outputs.DomainAdmin;
import com.pulumi.gandi.domains.outputs.DomainBilling;
import com.pulumi.gandi.domains.outputs.DomainOwner;
import com.pulumi.gandi.domains.outputs.DomainTech;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="gandi:domains/domain:Domain")
public class Domain extends com.pulumi.resources.CustomResource {
    @Export(name="admin", refs={DomainAdmin.class}, tree="[0]")
    private Output<DomainAdmin> admin;

    public Output<DomainAdmin> admin() {
        return this.admin;
    }
    /**
     * Should the domain autorenew
     * 
     */
    @Export(name="autorenew", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> autorenew;

    /**
     * @return Should the domain autorenew
     * 
     */
    public Output<Optional<Boolean>> autorenew() {
        return Codegen.optional(this.autorenew);
    }
    @Export(name="billing", refs={DomainBilling.class}, tree="[0]")
    private Output<DomainBilling> billing;

    public Output<DomainBilling> billing() {
        return this.billing;
    }
    /**
     * The FQDN of the domain
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The FQDN of the domain
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * A list of nameservers for the domain
     * 
     * @deprecated
     * This nameservers attribute will be removed on next major release: the nameservers resource has to be used instead.
     * See https://github.com/go-gandi/terraform-provider-gandi/issues/88 for details.
     * 
     */
    @Deprecated /* This nameservers attribute will be removed on next major release: the nameservers resource has to be used instead.
See https://github.com/go-gandi/terraform-provider-gandi/issues/88 for details. */
    @Export(name="nameservers", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> nameservers;

    /**
     * @return A list of nameservers for the domain
     * 
     */
    public Output<Optional<List<String>>> nameservers() {
        return Codegen.optional(this.nameservers);
    }
    @Export(name="owner", refs={DomainOwner.class}, tree="[0]")
    private Output<DomainOwner> owner;

    public Output<DomainOwner> owner() {
        return this.owner;
    }
    /**
     * A list of tags attached to the domain
     * 
     */
    @Export(name="tags", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> tags;

    /**
     * @return A list of tags attached to the domain
     * 
     */
    public Output<Optional<List<String>>> tags() {
        return Codegen.optional(this.tags);
    }
    @Export(name="tech", refs={DomainTech.class}, tree="[0]")
    private Output<DomainTech> tech;

    public Output<DomainTech> tech() {
        return this.tech;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Domain(java.lang.String name) {
        this(name, DomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Domain(java.lang.String name, DomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Domain(java.lang.String name, DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:domains/domain:Domain", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Domain(java.lang.String name, Output<java.lang.String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:domains/domain:Domain", name, state, makeResourceOptions(options, id), false);
    }

    private static DomainArgs makeArgs(DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Domain get(java.lang.String name, Output<java.lang.String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Domain(name, id, state, options);
    }
}
