// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.domains.inputs.GetDomainArgs;
import com.pulumi.gandi.domains.inputs.GetDomainPlainArgs;
import com.pulumi.gandi.domains.inputs.GetGlueRecordArgs;
import com.pulumi.gandi.domains.inputs.GetGlueRecordPlainArgs;
import com.pulumi.gandi.domains.outputs.GetDomainResult;
import com.pulumi.gandi.domains.outputs.GetGlueRecordResult;
import java.util.concurrent.CompletableFuture;

public final class DomainsFunctions {
    public static Output<GetDomainResult> getDomain(GetDomainArgs args) {
        return getDomain(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDomainResult> getDomainPlain(GetDomainPlainArgs args) {
        return getDomainPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDomainResult> getDomain(GetDomainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("gandi:domains/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDomainResult> getDomain(GetDomainArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("gandi:domains/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDomainResult> getDomainPlain(GetDomainPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("gandi:domains/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetGlueRecordResult> getGlueRecord(GetGlueRecordArgs args) {
        return getGlueRecord(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetGlueRecordResult> getGlueRecordPlain(GetGlueRecordPlainArgs args) {
        return getGlueRecordPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetGlueRecordResult> getGlueRecord(GetGlueRecordArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("gandi:domains/getGlueRecord:getGlueRecord", TypeShape.of(GetGlueRecordResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetGlueRecordResult> getGlueRecord(GetGlueRecordArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("gandi:domains/getGlueRecord:getGlueRecord", TypeShape.of(GetGlueRecordResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetGlueRecordResult> getGlueRecordPlain(GetGlueRecordPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("gandi:domains/getGlueRecord:getGlueRecord", TypeShape.of(GetGlueRecordResult.class), args, Utilities.withVersion(options));
    }
}
