// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GlueRecordArgs extends com.pulumi.resources.ResourceArgs {

    public static final GlueRecordArgs Empty = new GlueRecordArgs();

    /**
     * List of IP addresses
     * 
     */
    @Import(name="ips", required=true)
    private Output<List<String>> ips;

    /**
     * @return List of IP addresses
     * 
     */
    public Output<List<String>> ips() {
        return this.ips;
    }

    /**
     * Host name of the glue record
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Host name of the glue record
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Domain name
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return Domain name
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private GlueRecordArgs() {}

    private GlueRecordArgs(GlueRecordArgs $) {
        this.ips = $.ips;
        this.name = $.name;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GlueRecordArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GlueRecordArgs $;

        public Builder() {
            $ = new GlueRecordArgs();
        }

        public Builder(GlueRecordArgs defaults) {
            $ = new GlueRecordArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param ips List of IP addresses
         * 
         * @return builder
         * 
         */
        public Builder ips(Output<List<String>> ips) {
            $.ips = ips;
            return this;
        }

        /**
         * @param ips List of IP addresses
         * 
         * @return builder
         * 
         */
        public Builder ips(List<String> ips) {
            return ips(Output.of(ips));
        }

        /**
         * @param ips List of IP addresses
         * 
         * @return builder
         * 
         */
        public Builder ips(String... ips) {
            return ips(List.of(ips));
        }

        /**
         * @param name Host name of the glue record
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Host name of the glue record
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param zone Domain name
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone Domain name
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public GlueRecordArgs build() {
            if ($.ips == null) {
                throw new MissingRequiredPropertyException("GlueRecordArgs", "ips");
            }
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("GlueRecordArgs", "zone");
            }
            return $;
        }
    }

}
