// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMailboxResult {
    /**
     * @return Domain name
     * 
     */
    private String domain;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Mailbox ID
     * 
     */
    private String mailboxId;

    private GetMailboxResult() {}
    /**
     * @return Domain name
     * 
     */
    public String domain() {
        return this.domain;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Mailbox ID
     * 
     */
    public String mailboxId() {
        return this.mailboxId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMailboxResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private String id;
        private String mailboxId;
        public Builder() {}
        public Builder(GetMailboxResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.id = defaults.id;
    	      this.mailboxId = defaults.mailboxId;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            if (domain == null) {
              throw new MissingRequiredPropertyException("GetMailboxResult", "domain");
            }
            this.domain = domain;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetMailboxResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder mailboxId(String mailboxId) {
            if (mailboxId == null) {
              throw new MissingRequiredPropertyException("GetMailboxResult", "mailboxId");
            }
            this.mailboxId = mailboxId;
            return this;
        }
        public GetMailboxResult build() {
            final var _resultValue = new GetMailboxResult();
            _resultValue.domain = domain;
            _resultValue.id = id;
            _resultValue.mailboxId = mailboxId;
            return _resultValue;
        }
    }
}
