# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetGlueRecordResult',
    'AwaitableGetGlueRecordResult',
    'get_glue_record',
    'get_glue_record_output',
]

@pulumi.output_type
class GetGlueRecordResult:
    """
    A collection of values returned by getGlueRecord.
    """
    def __init__(__self__, id=None, ips=None, name=None, zone=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if ips and not isinstance(ips, list):
            raise TypeError("Expected argument 'ips' to be a list")
        pulumi.set(__self__, "ips", ips)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if zone and not isinstance(zone, str):
            raise TypeError("Expected argument 'zone' to be a str")
        pulumi.set(__self__, "zone", zone)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def ips(self) -> Sequence[_builtins.str]:
        """
        A list of the ip addresses provided for the glue record
        """
        return pulumi.get(self, "ips")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Host name of the glue record
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def zone(self) -> _builtins.str:
        """
        Domain name
        """
        return pulumi.get(self, "zone")


class AwaitableGetGlueRecordResult(GetGlueRecordResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGlueRecordResult(
            id=self.id,
            ips=self.ips,
            name=self.name,
            zone=self.zone)


def get_glue_record(name: Optional[_builtins.str] = None,
                    zone: Optional[_builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGlueRecordResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: Host name of the glue record
    :param _builtins.str zone: Domain name
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['zone'] = zone
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('gandi:domains/getGlueRecord:getGlueRecord', __args__, opts=opts, typ=GetGlueRecordResult).value

    return AwaitableGetGlueRecordResult(
        id=pulumi.get(__ret__, 'id'),
        ips=pulumi.get(__ret__, 'ips'),
        name=pulumi.get(__ret__, 'name'),
        zone=pulumi.get(__ret__, 'zone'))
def get_glue_record_output(name: Optional[pulumi.Input[_builtins.str]] = None,
                           zone: Optional[pulumi.Input[_builtins.str]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGlueRecordResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: Host name of the glue record
    :param _builtins.str zone: Domain name
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['zone'] = zone
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('gandi:domains/getGlueRecord:getGlueRecord', __args__, opts=opts, typ=GetGlueRecordResult)
    return __ret__.apply(lambda __response__: GetGlueRecordResult(
        id=pulumi.get(__response__, 'id'),
        ips=pulumi.get(__response__, 'ips'),
        name=pulumi.get(__response__, 'name'),
        zone=pulumi.get(__response__, 'zone')))
