// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainState extends com.pulumi.resources.ResourceArgs {

    public static final DomainState Empty = new DomainState();

    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     * 
     */
    @Import(name="automaticSnapshots")
    private @Nullable Output<Boolean> automaticSnapshots;

    /**
     * @return Enable or disable the automatic creation of snapshots when records are changed
     * 
     */
    public Optional<Output<Boolean>> automaticSnapshots() {
        return Optional.ofNullable(this.automaticSnapshots);
    }

    /**
     * The FQDN of the domain
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The FQDN of the domain
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The SOA TTL for the domain
     * 
     * @deprecated
     * This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
     * See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     * 
     */
    @Deprecated /* This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details. */
    @Import(name="ttl")
    private @Nullable Output<Integer> ttl;

    /**
     * @return The SOA TTL for the domain
     * 
     * @deprecated
     * This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
     * See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     * 
     */
    @Deprecated /* This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details. */
    public Optional<Output<Integer>> ttl() {
        return Optional.ofNullable(this.ttl);
    }

    private DomainState() {}

    private DomainState(DomainState $) {
        this.automaticSnapshots = $.automaticSnapshots;
        this.name = $.name;
        this.ttl = $.ttl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainState $;

        public Builder() {
            $ = new DomainState();
        }

        public Builder(DomainState defaults) {
            $ = new DomainState(Objects.requireNonNull(defaults));
        }

        /**
         * @param automaticSnapshots Enable or disable the automatic creation of snapshots when records are changed
         * 
         * @return builder
         * 
         */
        public Builder automaticSnapshots(@Nullable Output<Boolean> automaticSnapshots) {
            $.automaticSnapshots = automaticSnapshots;
            return this;
        }

        /**
         * @param automaticSnapshots Enable or disable the automatic creation of snapshots when records are changed
         * 
         * @return builder
         * 
         */
        public Builder automaticSnapshots(Boolean automaticSnapshots) {
            return automaticSnapshots(Output.of(automaticSnapshots));
        }

        /**
         * @param name The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param ttl The SOA TTL for the domain
         * 
         * @return builder
         * 
         * @deprecated
         * This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
         * See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
         * 
         */
        @Deprecated /* This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details. */
        public Builder ttl(@Nullable Output<Integer> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The SOA TTL for the domain
         * 
         * @return builder
         * 
         * @deprecated
         * This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
         * See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
         * 
         */
        @Deprecated /* This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details. */
        public Builder ttl(Integer ttl) {
            return ttl(Output.of(ttl));
        }

        public DomainState build() {
            return $;
        }
    }

}
