// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDomainNameserverPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDomainNameserverPlainArgs Empty = new GetDomainNameserverPlainArgs();

    /**
     * The FQDN of the domain
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The FQDN of the domain
     * 
     */
    public String name() {
        return this.name;
    }

    private GetDomainNameserverPlainArgs() {}

    private GetDomainNameserverPlainArgs(GetDomainNameserverPlainArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDomainNameserverPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDomainNameserverPlainArgs $;

        public Builder() {
            $ = new GetDomainNameserverPlainArgs();
        }

        public Builder(GetDomainNameserverPlainArgs defaults) {
            $ = new GetDomainNameserverPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetDomainNameserverPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetDomainNameserverPlainArgs", "name");
            }
            return $;
        }
    }

}
