// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDomainNameserverArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDomainNameserverArgs Empty = new GetDomainNameserverArgs();

    /**
     * The FQDN of the domain
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The FQDN of the domain
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private GetDomainNameserverArgs() {}

    private GetDomainNameserverArgs(GetDomainNameserverArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDomainNameserverArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDomainNameserverArgs $;

        public Builder() {
            $ = new GetDomainNameserverArgs();
        }

        public Builder(GetDomainNameserverArgs defaults) {
            $ = new GetDomainNameserverArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetDomainNameserverArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetDomainNameserverArgs", "name");
            }
            return $;
        }
    }

}
