// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ForwardingState extends com.pulumi.resources.ResourceArgs {

    public static final ForwardingState Empty = new ForwardingState();

    /**
     * Forwards to email addresses
     * 
     */
    @Import(name="destinations")
    private @Nullable Output<List<String>> destinations;

    /**
     * @return Forwards to email addresses
     * 
     */
    public Optional<Output<List<String>>> destinations() {
        return Optional.ofNullable(this.destinations);
    }

    /**
     * Account alias name
     * 
     */
    @Import(name="source")
    private @Nullable Output<String> source;

    /**
     * @return Account alias name
     * 
     */
    public Optional<Output<String>> source() {
        return Optional.ofNullable(this.source);
    }

    private ForwardingState() {}

    private ForwardingState(ForwardingState $) {
        this.destinations = $.destinations;
        this.source = $.source;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ForwardingState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ForwardingState $;

        public Builder() {
            $ = new ForwardingState();
        }

        public Builder(ForwardingState defaults) {
            $ = new ForwardingState(Objects.requireNonNull(defaults));
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(@Nullable Output<List<String>> destinations) {
            $.destinations = destinations;
            return this;
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(List<String> destinations) {
            return destinations(Output.of(destinations));
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(String... destinations) {
            return destinations(List.of(destinations));
        }

        /**
         * @param source Account alias name
         * 
         * @return builder
         * 
         */
        public Builder source(@Nullable Output<String> source) {
            $.source = source;
            return this;
        }

        /**
         * @param source Account alias name
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            return source(Output.of(source));
        }

        public ForwardingState build() {
            return $;
        }
    }

}
