// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetMailboxArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetMailboxArgs Empty = new GetMailboxArgs();

    /**
     * Domain name
     * 
     */
    @Import(name="domain", required=true)
    private Output<String> domain;

    /**
     * @return Domain name
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }

    /**
     * Mailbox ID
     * 
     */
    @Import(name="mailboxId", required=true)
    private Output<String> mailboxId;

    /**
     * @return Mailbox ID
     * 
     */
    public Output<String> mailboxId() {
        return this.mailboxId;
    }

    private GetMailboxArgs() {}

    private GetMailboxArgs(GetMailboxArgs $) {
        this.domain = $.domain;
        this.mailboxId = $.mailboxId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetMailboxArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetMailboxArgs $;

        public Builder() {
            $ = new GetMailboxArgs();
        }

        public Builder(GetMailboxArgs defaults) {
            $ = new GetMailboxArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param mailboxId Mailbox ID
         * 
         * @return builder
         * 
         */
        public Builder mailboxId(Output<String> mailboxId) {
            $.mailboxId = mailboxId;
            return this;
        }

        /**
         * @param mailboxId Mailbox ID
         * 
         * @return builder
         * 
         */
        public Builder mailboxId(String mailboxId) {
            return mailboxId(Output.of(mailboxId));
        }

        public GetMailboxArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("GetMailboxArgs", "domain");
            }
            if ($.mailboxId == null) {
                throw new MissingRequiredPropertyException("GetMailboxArgs", "mailboxId");
            }
            return $;
        }
    }

}
