// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DNSSecKeyState extends com.pulumi.resources.ResourceArgs {

    public static final DNSSecKeyState Empty = new DNSSecKeyState();

    /**
     * DNSSEC algorithm type
     * 
     */
    @Import(name="algorithm")
    private @Nullable Output<Integer> algorithm;

    /**
     * @return DNSSEC algorithm type
     * 
     */
    public Optional<Output<Integer>> algorithm() {
        return Optional.ofNullable(this.algorithm);
    }

    /**
     * Domain name
     * 
     */
    @Import(name="domain")
    private @Nullable Output<String> domain;

    /**
     * @return Domain name
     * 
     */
    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    /**
     * DNSSEC public key
     * 
     */
    @Import(name="publicKey")
    private @Nullable Output<String> publicKey;

    /**
     * @return DNSSEC public key
     * 
     */
    public Optional<Output<String>> publicKey() {
        return Optional.ofNullable(this.publicKey);
    }

    /**
     * DNSSEC key type
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return DNSSEC key type
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private DNSSecKeyState() {}

    private DNSSecKeyState(DNSSecKeyState $) {
        this.algorithm = $.algorithm;
        this.domain = $.domain;
        this.publicKey = $.publicKey;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DNSSecKeyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DNSSecKeyState $;

        public Builder() {
            $ = new DNSSecKeyState();
        }

        public Builder(DNSSecKeyState defaults) {
            $ = new DNSSecKeyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param algorithm DNSSEC algorithm type
         * 
         * @return builder
         * 
         */
        public Builder algorithm(@Nullable Output<Integer> algorithm) {
            $.algorithm = algorithm;
            return this;
        }

        /**
         * @param algorithm DNSSEC algorithm type
         * 
         * @return builder
         * 
         */
        public Builder algorithm(Integer algorithm) {
            return algorithm(Output.of(algorithm));
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param publicKey DNSSEC public key
         * 
         * @return builder
         * 
         */
        public Builder publicKey(@Nullable Output<String> publicKey) {
            $.publicKey = publicKey;
            return this;
        }

        /**
         * @param publicKey DNSSEC public key
         * 
         * @return builder
         * 
         */
        public Builder publicKey(String publicKey) {
            return publicKey(Output.of(publicKey));
        }

        /**
         * @param type DNSSEC key type
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type DNSSEC key type
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public DNSSecKeyState build() {
            return $;
        }
    }

}
