// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetGlueRecordPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetGlueRecordPlainArgs Empty = new GetGlueRecordPlainArgs();

    /**
     * Host name of the glue record
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return Host name of the glue record
     * 
     */
    public String name() {
        return this.name;
    }

    /**
     * Domain name
     * 
     */
    @Import(name="zone", required=true)
    private String zone;

    /**
     * @return Domain name
     * 
     */
    public String zone() {
        return this.zone;
    }

    private GetGlueRecordPlainArgs() {}

    private GetGlueRecordPlainArgs(GetGlueRecordPlainArgs $) {
        this.name = $.name;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGlueRecordPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGlueRecordPlainArgs $;

        public Builder() {
            $ = new GetGlueRecordPlainArgs();
        }

        public Builder(GetGlueRecordPlainArgs defaults) {
            $ = new GetGlueRecordPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Host name of the glue record
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        /**
         * @param zone Domain name
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            $.zone = zone;
            return this;
        }

        public GetGlueRecordPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetGlueRecordPlainArgs", "name");
            }
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("GetGlueRecordPlainArgs", "zone");
            }
            return $;
        }
    }

}
