// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NameserversState extends com.pulumi.resources.ResourceArgs {

    public static final NameserversState Empty = new NameserversState();

    /**
     * The FQDN of the domain
     * 
     */
    @Import(name="domain")
    private @Nullable Output<String> domain;

    /**
     * @return The FQDN of the domain
     * 
     */
    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    /**
     * A list of nameservers for the domain
     * 
     */
    @Import(name="nameservers")
    private @Nullable Output<List<String>> nameservers;

    /**
     * @return A list of nameservers for the domain
     * 
     */
    public Optional<Output<List<String>>> nameservers() {
        return Optional.ofNullable(this.nameservers);
    }

    private NameserversState() {}

    private NameserversState(NameserversState $) {
        this.domain = $.domain;
        this.nameservers = $.nameservers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NameserversState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NameserversState $;

        public Builder() {
            $ = new NameserversState();
        }

        public Builder(NameserversState defaults) {
            $ = new NameserversState(Objects.requireNonNull(defaults));
        }

        /**
         * @param domain The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param nameservers A list of nameservers for the domain
         * 
         * @return builder
         * 
         */
        public Builder nameservers(@Nullable Output<List<String>> nameservers) {
            $.nameservers = nameservers;
            return this;
        }

        /**
         * @param nameservers A list of nameservers for the domain
         * 
         * @return builder
         * 
         */
        public Builder nameservers(List<String> nameservers) {
            return nameservers(Output.of(nameservers));
        }

        /**
         * @param nameservers A list of nameservers for the domain
         * 
         * @return builder
         * 
         */
        public Builder nameservers(String... nameservers) {
            return nameservers(List.of(nameservers));
        }

        public NameserversState build() {
            return $;
        }
    }

}
