// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi.Email
{
    [GandiResourceType("gandi:email/forwarding:Forwarding")]
    public partial class Forwarding : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Forwards to email addresses
        /// </summary>
        [Output("destinations")]
        public Output<ImmutableArray<string>> Destinations { get; private set; } = null!;

        /// <summary>
        /// Account alias name
        /// </summary>
        [Output("source")]
        public Output<string> Source { get; private set; } = null!;


        /// <summary>
        /// Create a Forwarding resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Forwarding(string name, ForwardingArgs args, CustomResourceOptions? options = null)
            : base("gandi:email/forwarding:Forwarding", name, args ?? new ForwardingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Forwarding(string name, Input<string> id, ForwardingState? state = null, CustomResourceOptions? options = null)
            : base("gandi:email/forwarding:Forwarding", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Forwarding resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Forwarding Get(string name, Input<string> id, ForwardingState? state = null, CustomResourceOptions? options = null)
        {
            return new Forwarding(name, id, state, options);
        }
    }

    public sealed class ForwardingArgs : global::Pulumi.ResourceArgs
    {
        [Input("destinations", required: true)]
        private InputList<string>? _destinations;

        /// <summary>
        /// Forwards to email addresses
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// Account alias name
        /// </summary>
        [Input("source", required: true)]
        public Input<string> Source { get; set; } = null!;

        public ForwardingArgs()
        {
        }
        public static new ForwardingArgs Empty => new ForwardingArgs();
    }

    public sealed class ForwardingState : global::Pulumi.ResourceArgs
    {
        [Input("destinations")]
        private InputList<string>? _destinations;

        /// <summary>
        /// Forwards to email addresses
        /// </summary>
        public InputList<string> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<string>());
            set => _destinations = value;
        }

        /// <summary>
        /// Account alias name
        /// </summary>
        [Input("source")]
        public Input<string>? Source { get; set; }

        public ForwardingState()
        {
        }
        public static new ForwardingState Empty => new ForwardingState();
    }
}
