// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi.Email
{
    public static class GetMailbox
    {
        public static Task<GetMailboxResult> InvokeAsync(GetMailboxArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMailboxResult>("gandi:email/getMailbox:getMailbox", args ?? new GetMailboxArgs(), options.WithDefaults());

        public static Output<GetMailboxResult> Invoke(GetMailboxInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMailboxResult>("gandi:email/getMailbox:getMailbox", args ?? new GetMailboxInvokeArgs(), options.WithDefaults());

        public static Output<GetMailboxResult> Invoke(GetMailboxInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetMailboxResult>("gandi:email/getMailbox:getMailbox", args ?? new GetMailboxInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMailboxArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Domain name
        /// </summary>
        [Input("domain", required: true)]
        public string Domain { get; set; } = null!;

        /// <summary>
        /// Mailbox ID
        /// </summary>
        [Input("mailboxId", required: true)]
        public string MailboxId { get; set; } = null!;

        public GetMailboxArgs()
        {
        }
        public static new GetMailboxArgs Empty => new GetMailboxArgs();
    }

    public sealed class GetMailboxInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Domain name
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// Mailbox ID
        /// </summary>
        [Input("mailboxId", required: true)]
        public Input<string> MailboxId { get; set; } = null!;

        public GetMailboxInvokeArgs()
        {
        }
        public static new GetMailboxInvokeArgs Empty => new GetMailboxInvokeArgs();
    }


    [OutputType]
    public sealed class GetMailboxResult
    {
        /// <summary>
        /// Domain name
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Mailbox ID
        /// </summary>
        public readonly string MailboxId;

        [OutputConstructor]
        private GetMailboxResult(
            string domain,

            string id,

            string mailboxId)
        {
            Domain = domain;
            Id = id;
            MailboxId = mailboxId;
        }
    }
}
