// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package domains

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-gandi/sdk/v2/go/gandi/internal"
)

func LookupGlueRecord(ctx *pulumi.Context, args *LookupGlueRecordArgs, opts ...pulumi.InvokeOption) (*LookupGlueRecordResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGlueRecordResult
	err := ctx.Invoke("gandi:domains/getGlueRecord:getGlueRecord", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGlueRecord.
type LookupGlueRecordArgs struct {
	// Host name of the glue record
	Name string `pulumi:"name"`
	// Domain name
	Zone string `pulumi:"zone"`
}

// A collection of values returned by getGlueRecord.
type LookupGlueRecordResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A list of the ip addresses provided for the glue record
	Ips []string `pulumi:"ips"`
	// Host name of the glue record
	Name string `pulumi:"name"`
	// Domain name
	Zone string `pulumi:"zone"`
}

func LookupGlueRecordOutput(ctx *pulumi.Context, args LookupGlueRecordOutputArgs, opts ...pulumi.InvokeOption) LookupGlueRecordResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupGlueRecordResultOutput, error) {
			args := v.(LookupGlueRecordArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("gandi:domains/getGlueRecord:getGlueRecord", args, LookupGlueRecordResultOutput{}, options).(LookupGlueRecordResultOutput), nil
		}).(LookupGlueRecordResultOutput)
}

// A collection of arguments for invoking getGlueRecord.
type LookupGlueRecordOutputArgs struct {
	// Host name of the glue record
	Name pulumi.StringInput `pulumi:"name"`
	// Domain name
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (LookupGlueRecordOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGlueRecordArgs)(nil)).Elem()
}

// A collection of values returned by getGlueRecord.
type LookupGlueRecordResultOutput struct{ *pulumi.OutputState }

func (LookupGlueRecordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGlueRecordResult)(nil)).Elem()
}

func (o LookupGlueRecordResultOutput) ToLookupGlueRecordResultOutput() LookupGlueRecordResultOutput {
	return o
}

func (o LookupGlueRecordResultOutput) ToLookupGlueRecordResultOutputWithContext(ctx context.Context) LookupGlueRecordResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupGlueRecordResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Id }).(pulumi.StringOutput)
}

// A list of the ip addresses provided for the glue record
func (o LookupGlueRecordResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

// Host name of the glue record
func (o LookupGlueRecordResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Name }).(pulumi.StringOutput)
}

// Domain name
func (o LookupGlueRecordResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGlueRecordResultOutput{})
}
