// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.domains.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainAdmin {
    /**
     * @return City for the contact
     * 
     */
    private String city;
    /**
     * @return The two letter country code for the contact
     * 
     */
    private String country;
    /**
     * @return Whether or not to obfuscate contact data in WHOIS
     * 
     */
    private @Nullable Boolean dataObfuscated;
    /**
     * @return Contact email address
     * 
     */
    private String email;
    /**
     * @return Extra parameters, needed for some jurisdictions
     * 
     */
    private @Nullable Map<String,String> extraParameters;
    /**
     * @return Family name of the contact
     * 
     */
    private String familyName;
    /**
     * @return Given name of the contact
     * 
     */
    private String givenName;
    /**
     * @return Whether or not to obfuscate contact email in WHOIS
     * 
     */
    private @Nullable Boolean mailObfuscated;
    /**
     * @return The legal name of the organisation. Required for types other than person
     * 
     */
    private @Nullable String organisation;
    /**
     * @return Phone number for the contact
     * 
     */
    private String phone;
    /**
     * @return The state code for the contact
     * 
     */
    private @Nullable String state;
    /**
     * @return Street Address of the contact
     * 
     */
    private String streetAddr;
    /**
     * @return One of &#39;person&#39;, &#39;company&#39;, &#39;association&#39;, &#39;public body&#39;, or &#39;reseller&#39;
     * 
     */
    private String type;
    /**
     * @return Postal Code/Zipcode of the contact
     * 
     */
    private String zip;

    private DomainAdmin() {}
    /**
     * @return City for the contact
     * 
     */
    public String city() {
        return this.city;
    }
    /**
     * @return The two letter country code for the contact
     * 
     */
    public String country() {
        return this.country;
    }
    /**
     * @return Whether or not to obfuscate contact data in WHOIS
     * 
     */
    public Optional<Boolean> dataObfuscated() {
        return Optional.ofNullable(this.dataObfuscated);
    }
    /**
     * @return Contact email address
     * 
     */
    public String email() {
        return this.email;
    }
    /**
     * @return Extra parameters, needed for some jurisdictions
     * 
     */
    public Map<String,String> extraParameters() {
        return this.extraParameters == null ? Map.of() : this.extraParameters;
    }
    /**
     * @return Family name of the contact
     * 
     */
    public String familyName() {
        return this.familyName;
    }
    /**
     * @return Given name of the contact
     * 
     */
    public String givenName() {
        return this.givenName;
    }
    /**
     * @return Whether or not to obfuscate contact email in WHOIS
     * 
     */
    public Optional<Boolean> mailObfuscated() {
        return Optional.ofNullable(this.mailObfuscated);
    }
    /**
     * @return The legal name of the organisation. Required for types other than person
     * 
     */
    public Optional<String> organisation() {
        return Optional.ofNullable(this.organisation);
    }
    /**
     * @return Phone number for the contact
     * 
     */
    public String phone() {
        return this.phone;
    }
    /**
     * @return The state code for the contact
     * 
     */
    public Optional<String> state() {
        return Optional.ofNullable(this.state);
    }
    /**
     * @return Street Address of the contact
     * 
     */
    public String streetAddr() {
        return this.streetAddr;
    }
    /**
     * @return One of &#39;person&#39;, &#39;company&#39;, &#39;association&#39;, &#39;public body&#39;, or &#39;reseller&#39;
     * 
     */
    public String type() {
        return this.type;
    }
    /**
     * @return Postal Code/Zipcode of the contact
     * 
     */
    public String zip() {
        return this.zip;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainAdmin defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String city;
        private String country;
        private @Nullable Boolean dataObfuscated;
        private String email;
        private @Nullable Map<String,String> extraParameters;
        private String familyName;
        private String givenName;
        private @Nullable Boolean mailObfuscated;
        private @Nullable String organisation;
        private String phone;
        private @Nullable String state;
        private String streetAddr;
        private String type;
        private String zip;
        public Builder() {}
        public Builder(DomainAdmin defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.city = defaults.city;
    	      this.country = defaults.country;
    	      this.dataObfuscated = defaults.dataObfuscated;
    	      this.email = defaults.email;
    	      this.extraParameters = defaults.extraParameters;
    	      this.familyName = defaults.familyName;
    	      this.givenName = defaults.givenName;
    	      this.mailObfuscated = defaults.mailObfuscated;
    	      this.organisation = defaults.organisation;
    	      this.phone = defaults.phone;
    	      this.state = defaults.state;
    	      this.streetAddr = defaults.streetAddr;
    	      this.type = defaults.type;
    	      this.zip = defaults.zip;
        }

        @CustomType.Setter
        public Builder city(String city) {
            if (city == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "city");
            }
            this.city = city;
            return this;
        }
        @CustomType.Setter
        public Builder country(String country) {
            if (country == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "country");
            }
            this.country = country;
            return this;
        }
        @CustomType.Setter
        public Builder dataObfuscated(@Nullable Boolean dataObfuscated) {

            this.dataObfuscated = dataObfuscated;
            return this;
        }
        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder extraParameters(@Nullable Map<String,String> extraParameters) {

            this.extraParameters = extraParameters;
            return this;
        }
        @CustomType.Setter
        public Builder familyName(String familyName) {
            if (familyName == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "familyName");
            }
            this.familyName = familyName;
            return this;
        }
        @CustomType.Setter
        public Builder givenName(String givenName) {
            if (givenName == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "givenName");
            }
            this.givenName = givenName;
            return this;
        }
        @CustomType.Setter
        public Builder mailObfuscated(@Nullable Boolean mailObfuscated) {

            this.mailObfuscated = mailObfuscated;
            return this;
        }
        @CustomType.Setter
        public Builder organisation(@Nullable String organisation) {

            this.organisation = organisation;
            return this;
        }
        @CustomType.Setter
        public Builder phone(String phone) {
            if (phone == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "phone");
            }
            this.phone = phone;
            return this;
        }
        @CustomType.Setter
        public Builder state(@Nullable String state) {

            this.state = state;
            return this;
        }
        @CustomType.Setter
        public Builder streetAddr(String streetAddr) {
            if (streetAddr == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "streetAddr");
            }
            this.streetAddr = streetAddr;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder zip(String zip) {
            if (zip == null) {
              throw new MissingRequiredPropertyException("DomainAdmin", "zip");
            }
            this.zip = zip;
            return this;
        }
        public DomainAdmin build() {
            final var _resultValue = new DomainAdmin();
            _resultValue.city = city;
            _resultValue.country = country;
            _resultValue.dataObfuscated = dataObfuscated;
            _resultValue.email = email;
            _resultValue.extraParameters = extraParameters;
            _resultValue.familyName = familyName;
            _resultValue.givenName = givenName;
            _resultValue.mailObfuscated = mailObfuscated;
            _resultValue.organisation = organisation;
            _resultValue.phone = phone;
            _resultValue.state = state;
            _resultValue.streetAddr = streetAddr;
            _resultValue.type = type;
            _resultValue.zip = zip;
            return _resultValue;
        }
    }
}
