// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getMailbox(args: GetMailboxArgs, opts?: pulumi.InvokeOptions): Promise<GetMailboxResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gandi:email/getMailbox:getMailbox", {
        "domain": args.domain,
        "mailboxId": args.mailboxId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMailbox.
 */
export interface GetMailboxArgs {
    /**
     * Domain name
     */
    domain: string;
    /**
     * Mailbox ID
     */
    mailboxId: string;
}

/**
 * A collection of values returned by getMailbox.
 */
export interface GetMailboxResult {
    /**
     * Domain name
     */
    readonly domain: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Mailbox ID
     */
    readonly mailboxId: string;
}
export function getMailboxOutput(args: GetMailboxOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMailboxResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("gandi:email/getMailbox:getMailbox", {
        "domain": args.domain,
        "mailboxId": args.mailboxId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMailbox.
 */
export interface GetMailboxOutputArgs {
    /**
     * Domain name
     */
    domain: pulumi.Input<string>;
    /**
     * Mailbox ID
     */
    mailboxId: pulumi.Input<string>;
}
