// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package simplehosting

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-gandi/sdk/v2/go/gandi/internal"
)

type Instance struct {
	pulumi.CustomResourceState

	// The name of the database type ('mysql' or 'pgsql')
	DatabaseName pulumi.StringOutput `pulumi:"databaseName"`
	// The name of the language ('php', 'python', 'nodejs' or 'ruby')
	LanguageName pulumi.StringOutput `pulumi:"languageName"`
	// The datacenter location of the instance ('FR' or 'LU')
	Location pulumi.StringOutput `pulumi:"location"`
	// The name of the SimpleHosting instance
	Name pulumi.StringOutput `pulumi:"name"`
	// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
	Size pulumi.StringOutput `pulumi:"size"`
}

// NewInstance registers a new resource with the given unique name, arguments, and options.
func NewInstance(ctx *pulumi.Context,
	name string, args *InstanceArgs, opts ...pulumi.ResourceOption) (*Instance, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DatabaseName == nil {
		return nil, errors.New("invalid value for required argument 'DatabaseName'")
	}
	if args.LanguageName == nil {
		return nil, errors.New("invalid value for required argument 'LanguageName'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.Size == nil {
		return nil, errors.New("invalid value for required argument 'Size'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Instance
	err := ctx.RegisterResource("gandi:simplehosting/instance:Instance", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstance gets an existing Instance resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstance(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceState, opts ...pulumi.ResourceOption) (*Instance, error) {
	var resource Instance
	err := ctx.ReadResource("gandi:simplehosting/instance:Instance", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Instance resources.
type instanceState struct {
	// The name of the database type ('mysql' or 'pgsql')
	DatabaseName *string `pulumi:"databaseName"`
	// The name of the language ('php', 'python', 'nodejs' or 'ruby')
	LanguageName *string `pulumi:"languageName"`
	// The datacenter location of the instance ('FR' or 'LU')
	Location *string `pulumi:"location"`
	// The name of the SimpleHosting instance
	Name *string `pulumi:"name"`
	// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
	Size *string `pulumi:"size"`
}

type InstanceState struct {
	// The name of the database type ('mysql' or 'pgsql')
	DatabaseName pulumi.StringPtrInput
	// The name of the language ('php', 'python', 'nodejs' or 'ruby')
	LanguageName pulumi.StringPtrInput
	// The datacenter location of the instance ('FR' or 'LU')
	Location pulumi.StringPtrInput
	// The name of the SimpleHosting instance
	Name pulumi.StringPtrInput
	// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
	Size pulumi.StringPtrInput
}

func (InstanceState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceState)(nil)).Elem()
}

type instanceArgs struct {
	// The name of the database type ('mysql' or 'pgsql')
	DatabaseName string `pulumi:"databaseName"`
	// The name of the language ('php', 'python', 'nodejs' or 'ruby')
	LanguageName string `pulumi:"languageName"`
	// The datacenter location of the instance ('FR' or 'LU')
	Location string `pulumi:"location"`
	// The name of the SimpleHosting instance
	Name *string `pulumi:"name"`
	// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
	Size string `pulumi:"size"`
}

// The set of arguments for constructing a Instance resource.
type InstanceArgs struct {
	// The name of the database type ('mysql' or 'pgsql')
	DatabaseName pulumi.StringInput
	// The name of the language ('php', 'python', 'nodejs' or 'ruby')
	LanguageName pulumi.StringInput
	// The datacenter location of the instance ('FR' or 'LU')
	Location pulumi.StringInput
	// The name of the SimpleHosting instance
	Name pulumi.StringPtrInput
	// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
	Size pulumi.StringInput
}

func (InstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceArgs)(nil)).Elem()
}

type InstanceInput interface {
	pulumi.Input

	ToInstanceOutput() InstanceOutput
	ToInstanceOutputWithContext(ctx context.Context) InstanceOutput
}

func (*Instance) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (i *Instance) ToInstanceOutput() InstanceOutput {
	return i.ToInstanceOutputWithContext(context.Background())
}

func (i *Instance) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceOutput)
}

// InstanceArrayInput is an input type that accepts InstanceArray and InstanceArrayOutput values.
// You can construct a concrete instance of `InstanceArrayInput` via:
//
//	InstanceArray{ InstanceArgs{...} }
type InstanceArrayInput interface {
	pulumi.Input

	ToInstanceArrayOutput() InstanceArrayOutput
	ToInstanceArrayOutputWithContext(context.Context) InstanceArrayOutput
}

type InstanceArray []InstanceInput

func (InstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (i InstanceArray) ToInstanceArrayOutput() InstanceArrayOutput {
	return i.ToInstanceArrayOutputWithContext(context.Background())
}

func (i InstanceArray) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceArrayOutput)
}

// InstanceMapInput is an input type that accepts InstanceMap and InstanceMapOutput values.
// You can construct a concrete instance of `InstanceMapInput` via:
//
//	InstanceMap{ "key": InstanceArgs{...} }
type InstanceMapInput interface {
	pulumi.Input

	ToInstanceMapOutput() InstanceMapOutput
	ToInstanceMapOutputWithContext(context.Context) InstanceMapOutput
}

type InstanceMap map[string]InstanceInput

func (InstanceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (i InstanceMap) ToInstanceMapOutput() InstanceMapOutput {
	return i.ToInstanceMapOutputWithContext(context.Background())
}

func (i InstanceMap) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceMapOutput)
}

type InstanceOutput struct{ *pulumi.OutputState }

func (InstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (o InstanceOutput) ToInstanceOutput() InstanceOutput {
	return o
}

func (o InstanceOutput) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return o
}

// The name of the database type ('mysql' or 'pgsql')
func (o InstanceOutput) DatabaseName() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.DatabaseName }).(pulumi.StringOutput)
}

// The name of the language ('php', 'python', 'nodejs' or 'ruby')
func (o InstanceOutput) LanguageName() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.LanguageName }).(pulumi.StringOutput)
}

// The datacenter location of the instance ('FR' or 'LU')
func (o InstanceOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

// The name of the SimpleHosting instance
func (o InstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
func (o InstanceOutput) Size() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Size }).(pulumi.StringOutput)
}

type InstanceArrayOutput struct{ *pulumi.OutputState }

func (InstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Instance)(nil)).Elem()
}

func (o InstanceArrayOutput) ToInstanceArrayOutput() InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) ToInstanceArrayOutputWithContext(ctx context.Context) InstanceArrayOutput {
	return o
}

func (o InstanceArrayOutput) Index(i pulumi.IntInput) InstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].([]*Instance)[vs[1].(int)]
	}).(InstanceOutput)
}

type InstanceMapOutput struct{ *pulumi.OutputState }

func (InstanceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Instance)(nil)).Elem()
}

func (o InstanceMapOutput) ToInstanceMapOutput() InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) ToInstanceMapOutputWithContext(ctx context.Context) InstanceMapOutput {
	return o
}

func (o InstanceMapOutput) MapIndex(k pulumi.StringInput) InstanceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Instance {
		return vs[0].(map[string]*Instance)[vs[1].(string)]
	}).(InstanceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceInput)(nil)).Elem(), &Instance{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceArrayInput)(nil)).Elem(), InstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceMapInput)(nil)).Elem(), InstanceMap{})
	pulumi.RegisterOutputType(InstanceOutput{})
	pulumi.RegisterOutputType(InstanceArrayOutput{})
	pulumi.RegisterOutputType(InstanceMapOutput{})
}
