// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package simplehosting

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-gandi/sdk/v2/go/gandi/internal"
)

type VHost struct {
	pulumi.CustomResourceState

	// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
	Application pulumi.StringPtrOutput `pulumi:"application"`
	// The ID of the created free certificate
	CertificateId pulumi.StringOutput `pulumi:"certificateId"`
	// The FQDN of the Vhost
	Fqdn pulumi.StringOutput `pulumi:"fqdn"`
	// The ID of the SimpleHosting instance
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// Whether to alter the linked DNS Zone
	LinkedDnsZoneAlteration pulumi.BoolPtrOutput `pulumi:"linkedDnsZoneAlteration"`
}

// NewVHost registers a new resource with the given unique name, arguments, and options.
func NewVHost(ctx *pulumi.Context,
	name string, args *VHostArgs, opts ...pulumi.ResourceOption) (*VHost, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Fqdn == nil {
		return nil, errors.New("invalid value for required argument 'Fqdn'")
	}
	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VHost
	err := ctx.RegisterResource("gandi:simplehosting/vHost:VHost", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVHost gets an existing VHost resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVHost(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VHostState, opts ...pulumi.ResourceOption) (*VHost, error) {
	var resource VHost
	err := ctx.ReadResource("gandi:simplehosting/vHost:VHost", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VHost resources.
type vhostState struct {
	// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
	Application *string `pulumi:"application"`
	// The ID of the created free certificate
	CertificateId *string `pulumi:"certificateId"`
	// The FQDN of the Vhost
	Fqdn *string `pulumi:"fqdn"`
	// The ID of the SimpleHosting instance
	InstanceId *string `pulumi:"instanceId"`
	// Whether to alter the linked DNS Zone
	LinkedDnsZoneAlteration *bool `pulumi:"linkedDnsZoneAlteration"`
}

type VHostState struct {
	// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
	Application pulumi.StringPtrInput
	// The ID of the created free certificate
	CertificateId pulumi.StringPtrInput
	// The FQDN of the Vhost
	Fqdn pulumi.StringPtrInput
	// The ID of the SimpleHosting instance
	InstanceId pulumi.StringPtrInput
	// Whether to alter the linked DNS Zone
	LinkedDnsZoneAlteration pulumi.BoolPtrInput
}

func (VHostState) ElementType() reflect.Type {
	return reflect.TypeOf((*vhostState)(nil)).Elem()
}

type vhostArgs struct {
	// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
	Application *string `pulumi:"application"`
	// The FQDN of the Vhost
	Fqdn string `pulumi:"fqdn"`
	// The ID of the SimpleHosting instance
	InstanceId string `pulumi:"instanceId"`
	// Whether to alter the linked DNS Zone
	LinkedDnsZoneAlteration *bool `pulumi:"linkedDnsZoneAlteration"`
}

// The set of arguments for constructing a VHost resource.
type VHostArgs struct {
	// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
	Application pulumi.StringPtrInput
	// The FQDN of the Vhost
	Fqdn pulumi.StringInput
	// The ID of the SimpleHosting instance
	InstanceId pulumi.StringInput
	// Whether to alter the linked DNS Zone
	LinkedDnsZoneAlteration pulumi.BoolPtrInput
}

func (VHostArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vhostArgs)(nil)).Elem()
}

type VHostInput interface {
	pulumi.Input

	ToVHostOutput() VHostOutput
	ToVHostOutputWithContext(ctx context.Context) VHostOutput
}

func (*VHost) ElementType() reflect.Type {
	return reflect.TypeOf((**VHost)(nil)).Elem()
}

func (i *VHost) ToVHostOutput() VHostOutput {
	return i.ToVHostOutputWithContext(context.Background())
}

func (i *VHost) ToVHostOutputWithContext(ctx context.Context) VHostOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VHostOutput)
}

// VHostArrayInput is an input type that accepts VHostArray and VHostArrayOutput values.
// You can construct a concrete instance of `VHostArrayInput` via:
//
//	VHostArray{ VHostArgs{...} }
type VHostArrayInput interface {
	pulumi.Input

	ToVHostArrayOutput() VHostArrayOutput
	ToVHostArrayOutputWithContext(context.Context) VHostArrayOutput
}

type VHostArray []VHostInput

func (VHostArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VHost)(nil)).Elem()
}

func (i VHostArray) ToVHostArrayOutput() VHostArrayOutput {
	return i.ToVHostArrayOutputWithContext(context.Background())
}

func (i VHostArray) ToVHostArrayOutputWithContext(ctx context.Context) VHostArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VHostArrayOutput)
}

// VHostMapInput is an input type that accepts VHostMap and VHostMapOutput values.
// You can construct a concrete instance of `VHostMapInput` via:
//
//	VHostMap{ "key": VHostArgs{...} }
type VHostMapInput interface {
	pulumi.Input

	ToVHostMapOutput() VHostMapOutput
	ToVHostMapOutputWithContext(context.Context) VHostMapOutput
}

type VHostMap map[string]VHostInput

func (VHostMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VHost)(nil)).Elem()
}

func (i VHostMap) ToVHostMapOutput() VHostMapOutput {
	return i.ToVHostMapOutputWithContext(context.Background())
}

func (i VHostMap) ToVHostMapOutputWithContext(ctx context.Context) VHostMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VHostMapOutput)
}

type VHostOutput struct{ *pulumi.OutputState }

func (VHostOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VHost)(nil)).Elem()
}

func (o VHostOutput) ToVHostOutput() VHostOutput {
	return o
}

func (o VHostOutput) ToVHostOutputWithContext(ctx context.Context) VHostOutput {
	return o
}

// The name of an application to install ('grav', 'matomo', 'nextcloud', 'prestashop', 'wordpress')
func (o VHostOutput) Application() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VHost) pulumi.StringPtrOutput { return v.Application }).(pulumi.StringPtrOutput)
}

// The ID of the created free certificate
func (o VHostOutput) CertificateId() pulumi.StringOutput {
	return o.ApplyT(func(v *VHost) pulumi.StringOutput { return v.CertificateId }).(pulumi.StringOutput)
}

// The FQDN of the Vhost
func (o VHostOutput) Fqdn() pulumi.StringOutput {
	return o.ApplyT(func(v *VHost) pulumi.StringOutput { return v.Fqdn }).(pulumi.StringOutput)
}

// The ID of the SimpleHosting instance
func (o VHostOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *VHost) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// Whether to alter the linked DNS Zone
func (o VHostOutput) LinkedDnsZoneAlteration() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *VHost) pulumi.BoolPtrOutput { return v.LinkedDnsZoneAlteration }).(pulumi.BoolPtrOutput)
}

type VHostArrayOutput struct{ *pulumi.OutputState }

func (VHostArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VHost)(nil)).Elem()
}

func (o VHostArrayOutput) ToVHostArrayOutput() VHostArrayOutput {
	return o
}

func (o VHostArrayOutput) ToVHostArrayOutputWithContext(ctx context.Context) VHostArrayOutput {
	return o
}

func (o VHostArrayOutput) Index(i pulumi.IntInput) VHostOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VHost {
		return vs[0].([]*VHost)[vs[1].(int)]
	}).(VHostOutput)
}

type VHostMapOutput struct{ *pulumi.OutputState }

func (VHostMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VHost)(nil)).Elem()
}

func (o VHostMapOutput) ToVHostMapOutput() VHostMapOutput {
	return o
}

func (o VHostMapOutput) ToVHostMapOutputWithContext(ctx context.Context) VHostMapOutput {
	return o
}

func (o VHostMapOutput) MapIndex(k pulumi.StringInput) VHostOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VHost {
		return vs[0].(map[string]*VHost)[vs[1].(string)]
	}).(VHostOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VHostInput)(nil)).Elem(), &VHost{})
	pulumi.RegisterInputType(reflect.TypeOf((*VHostArrayInput)(nil)).Elem(), VHostArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VHostMapInput)(nil)).Elem(), VHostMap{})
	pulumi.RegisterOutputType(VHostOutput{})
	pulumi.RegisterOutputType(VHostArrayOutput{})
	pulumi.RegisterOutputType(VHostMapOutput{})
}
