// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDomainNameserverResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The FQDN of the domain
     * 
     */
    private String name;
    /**
     * @return A list of nameservers for the domain
     * 
     */
    private List<String> nameservers;

    private GetDomainNameserverResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The FQDN of the domain
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return A list of nameservers for the domain
     * 
     */
    public List<String> nameservers() {
        return this.nameservers;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainNameserverResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String name;
        private List<String> nameservers;
        public Builder() {}
        public Builder(GetDomainNameserverResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.nameservers = defaults.nameservers;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDomainNameserverResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetDomainNameserverResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder nameservers(List<String> nameservers) {
            if (nameservers == null) {
              throw new MissingRequiredPropertyException("GetDomainNameserverResult", "nameservers");
            }
            this.nameservers = nameservers;
            return this;
        }
        public Builder nameservers(String... nameservers) {
            return nameservers(List.of(nameservers));
        }
        public GetDomainNameserverResult build() {
            final var _resultValue = new GetDomainNameserverResult();
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.nameservers = nameservers;
            return _resultValue;
        }
    }
}
