// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("gandi");
/**
 * Prevent the Domain provider from taking certain actions
 * 
 */
    public Optional<Boolean> dryRun() {
        return Codegen.booleanProp("dryRun").config(config).get();
    }
/**
 * (DEPRECATED) A Gandi API key
 * 
 */
    public Optional<String> key() {
        return Codegen.stringProp("key").config(config).env("GANDI_KEY").get();
    }
/**
 * A Gandi API Personal Access Token
 * 
 */
    public Optional<String> personalAccessToken() {
        return Codegen.stringProp("personalAccessToken").config(config).get();
    }
/**
 * (DEPRECATED) A Gandi Sharing ID
 * 
 */
    public Optional<String> sharingId() {
        return Codegen.stringProp("sharingId").config(config).get();
    }
/**
 * The Gandi API URL
 * 
 */
    public Optional<String> url() {
        return Codegen.stringProp("url").config(config).get();
    }
}
