# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetDomainNameserverResult',
    'AwaitableGetDomainNameserverResult',
    'get_domain_nameserver',
    'get_domain_nameserver_output',
]

@pulumi.output_type
class GetDomainNameserverResult:
    """
    A collection of values returned by getDomainNameserver.
    """
    def __init__(__self__, id=None, name=None, nameservers=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if nameservers and not isinstance(nameservers, list):
            raise TypeError("Expected argument 'nameservers' to be a list")
        pulumi.set(__self__, "nameservers", nameservers)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The FQDN of the domain
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def nameservers(self) -> Sequence[_builtins.str]:
        """
        A list of nameservers for the domain
        """
        return pulumi.get(self, "nameservers")


class AwaitableGetDomainNameserverResult(GetDomainNameserverResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDomainNameserverResult(
            id=self.id,
            name=self.name,
            nameservers=self.nameservers)


def get_domain_nameserver(name: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDomainNameserverResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: The FQDN of the domain
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('gandi:livedns/getDomainNameserver:getDomainNameserver', __args__, opts=opts, typ=GetDomainNameserverResult).value

    return AwaitableGetDomainNameserverResult(
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        nameservers=pulumi.get(__ret__, 'nameservers'))
def get_domain_nameserver_output(name: Optional[pulumi.Input[_builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDomainNameserverResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: The FQDN of the domain
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('gandi:livedns/getDomainNameserver:getDomainNameserver', __args__, opts=opts, typ=GetDomainNameserverResult)
    return __ret__.apply(lambda __response__: GetDomainNameserverResult(
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        nameservers=pulumi.get(__response__, 'nameservers')))
