// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.simplehosting;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.simplehosting.InstanceArgs;
import com.pulumi.gandi.simplehosting.inputs.InstanceState;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="gandi:simplehosting/instance:Instance")
public class Instance extends com.pulumi.resources.CustomResource {
    /**
     * The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
     * 
     */
    @Export(name="databaseName", refs={String.class}, tree="[0]")
    private Output<String> databaseName;

    /**
     * @return The name of the database type (&#39;mysql&#39; or &#39;pgsql&#39;)
     * 
     */
    public Output<String> databaseName() {
        return this.databaseName;
    }
    /**
     * The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
     * 
     */
    @Export(name="languageName", refs={String.class}, tree="[0]")
    private Output<String> languageName;

    /**
     * @return The name of the language (&#39;php&#39;, &#39;python&#39;, &#39;nodejs&#39; or &#39;ruby&#39;)
     * 
     */
    public Output<String> languageName() {
        return this.languageName;
    }
    /**
     * The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
     * 
     */
    @Export(name="location", refs={String.class}, tree="[0]")
    private Output<String> location;

    /**
     * @return The datacenter location of the instance (&#39;FR&#39; or &#39;LU&#39;)
     * 
     */
    public Output<String> location() {
        return this.location;
    }
    /**
     * The name of the SimpleHosting instance
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the SimpleHosting instance
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
     * 
     */
    @Export(name="size", refs={String.class}, tree="[0]")
    private Output<String> size;

    /**
     * @return The size of the SimpleHosting instance (&#39;s+&#39;, &#39;m&#39;, &#39;l&#39; or &#39;xxl&#39;)
     * 
     */
    public Output<String> size() {
        return this.size;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Instance(java.lang.String name) {
        this(name, InstanceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Instance(java.lang.String name, InstanceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Instance(java.lang.String name, InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:simplehosting/instance:Instance", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Instance(java.lang.String name, Output<java.lang.String> id, @Nullable InstanceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("gandi:simplehosting/instance:Instance", name, state, makeResourceOptions(options, id), false);
    }

    private static InstanceArgs makeArgs(InstanceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? InstanceArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumiverse")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Instance get(java.lang.String name, Output<java.lang.String> id, @Nullable InstanceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Instance(name, id, state, options);
    }
}
