// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.simplehosting;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VHostArgs extends com.pulumi.resources.ResourceArgs {

    public static final VHostArgs Empty = new VHostArgs();

    /**
     * The name of an application to install (&#39;grav&#39;, &#39;matomo&#39;, &#39;nextcloud&#39;, &#39;prestashop&#39;, &#39;wordpress&#39;)
     * 
     */
    @Import(name="application")
    private @Nullable Output<String> application;

    /**
     * @return The name of an application to install (&#39;grav&#39;, &#39;matomo&#39;, &#39;nextcloud&#39;, &#39;prestashop&#39;, &#39;wordpress&#39;)
     * 
     */
    public Optional<Output<String>> application() {
        return Optional.ofNullable(this.application);
    }

    /**
     * The FQDN of the Vhost
     * 
     */
    @Import(name="fqdn", required=true)
    private Output<String> fqdn;

    /**
     * @return The FQDN of the Vhost
     * 
     */
    public Output<String> fqdn() {
        return this.fqdn;
    }

    /**
     * The ID of the SimpleHosting instance
     * 
     */
    @Import(name="instanceId", required=true)
    private Output<String> instanceId;

    /**
     * @return The ID of the SimpleHosting instance
     * 
     */
    public Output<String> instanceId() {
        return this.instanceId;
    }

    /**
     * Whether to alter the linked DNS Zone
     * 
     */
    @Import(name="linkedDnsZoneAlteration")
    private @Nullable Output<Boolean> linkedDnsZoneAlteration;

    /**
     * @return Whether to alter the linked DNS Zone
     * 
     */
    public Optional<Output<Boolean>> linkedDnsZoneAlteration() {
        return Optional.ofNullable(this.linkedDnsZoneAlteration);
    }

    private VHostArgs() {}

    private VHostArgs(VHostArgs $) {
        this.application = $.application;
        this.fqdn = $.fqdn;
        this.instanceId = $.instanceId;
        this.linkedDnsZoneAlteration = $.linkedDnsZoneAlteration;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VHostArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VHostArgs $;

        public Builder() {
            $ = new VHostArgs();
        }

        public Builder(VHostArgs defaults) {
            $ = new VHostArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param application The name of an application to install (&#39;grav&#39;, &#39;matomo&#39;, &#39;nextcloud&#39;, &#39;prestashop&#39;, &#39;wordpress&#39;)
         * 
         * @return builder
         * 
         */
        public Builder application(@Nullable Output<String> application) {
            $.application = application;
            return this;
        }

        /**
         * @param application The name of an application to install (&#39;grav&#39;, &#39;matomo&#39;, &#39;nextcloud&#39;, &#39;prestashop&#39;, &#39;wordpress&#39;)
         * 
         * @return builder
         * 
         */
        public Builder application(String application) {
            return application(Output.of(application));
        }

        /**
         * @param fqdn The FQDN of the Vhost
         * 
         * @return builder
         * 
         */
        public Builder fqdn(Output<String> fqdn) {
            $.fqdn = fqdn;
            return this;
        }

        /**
         * @param fqdn The FQDN of the Vhost
         * 
         * @return builder
         * 
         */
        public Builder fqdn(String fqdn) {
            return fqdn(Output.of(fqdn));
        }

        /**
         * @param instanceId The ID of the SimpleHosting instance
         * 
         * @return builder
         * 
         */
        public Builder instanceId(Output<String> instanceId) {
            $.instanceId = instanceId;
            return this;
        }

        /**
         * @param instanceId The ID of the SimpleHosting instance
         * 
         * @return builder
         * 
         */
        public Builder instanceId(String instanceId) {
            return instanceId(Output.of(instanceId));
        }

        /**
         * @param linkedDnsZoneAlteration Whether to alter the linked DNS Zone
         * 
         * @return builder
         * 
         */
        public Builder linkedDnsZoneAlteration(@Nullable Output<Boolean> linkedDnsZoneAlteration) {
            $.linkedDnsZoneAlteration = linkedDnsZoneAlteration;
            return this;
        }

        /**
         * @param linkedDnsZoneAlteration Whether to alter the linked DNS Zone
         * 
         * @return builder
         * 
         */
        public Builder linkedDnsZoneAlteration(Boolean linkedDnsZoneAlteration) {
            return linkedDnsZoneAlteration(Output.of(linkedDnsZoneAlteration));
        }

        public VHostArgs build() {
            if ($.fqdn == null) {
                throw new MissingRequiredPropertyException("VHostArgs", "fqdn");
            }
            if ($.instanceId == null) {
                throw new MissingRequiredPropertyException("VHostArgs", "instanceId");
            }
            return $;
        }
    }

}
