// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.email.inputs.GetMailboxArgs;
import com.pulumi.gandi.email.inputs.GetMailboxPlainArgs;
import com.pulumi.gandi.email.outputs.GetMailboxResult;
import java.util.concurrent.CompletableFuture;

public final class EmailFunctions {
    public static Output<GetMailboxResult> getMailbox(GetMailboxArgs args) {
        return getMailbox(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetMailboxResult> getMailboxPlain(GetMailboxPlainArgs args) {
        return getMailboxPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetMailboxResult> getMailbox(GetMailboxArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("gandi:email/getMailbox:getMailbox", TypeShape.of(GetMailboxResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetMailboxResult> getMailbox(GetMailboxArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("gandi:email/getMailbox:getMailbox", TypeShape.of(GetMailboxResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetMailboxResult> getMailboxPlain(GetMailboxPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("gandi:email/getMailbox:getMailbox", TypeShape.of(GetMailboxResult.class), args, Utilities.withVersion(options));
    }
}
