// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class ForwardingArgs extends com.pulumi.resources.ResourceArgs {

    public static final ForwardingArgs Empty = new ForwardingArgs();

    /**
     * Forwards to email addresses
     * 
     */
    @Import(name="destinations", required=true)
    private Output<List<String>> destinations;

    /**
     * @return Forwards to email addresses
     * 
     */
    public Output<List<String>> destinations() {
        return this.destinations;
    }

    /**
     * Account alias name
     * 
     */
    @Import(name="source", required=true)
    private Output<String> source;

    /**
     * @return Account alias name
     * 
     */
    public Output<String> source() {
        return this.source;
    }

    private ForwardingArgs() {}

    private ForwardingArgs(ForwardingArgs $) {
        this.destinations = $.destinations;
        this.source = $.source;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ForwardingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ForwardingArgs $;

        public Builder() {
            $ = new ForwardingArgs();
        }

        public Builder(ForwardingArgs defaults) {
            $ = new ForwardingArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(Output<List<String>> destinations) {
            $.destinations = destinations;
            return this;
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(List<String> destinations) {
            return destinations(Output.of(destinations));
        }

        /**
         * @param destinations Forwards to email addresses
         * 
         * @return builder
         * 
         */
        public Builder destinations(String... destinations) {
            return destinations(List.of(destinations));
        }

        /**
         * @param source Account alias name
         * 
         * @return builder
         * 
         */
        public Builder source(Output<String> source) {
            $.source = source;
            return this;
        }

        /**
         * @param source Account alias name
         * 
         * @return builder
         * 
         */
        public Builder source(String source) {
            return source(Output.of(source));
        }

        public ForwardingArgs build() {
            if ($.destinations == null) {
                throw new MissingRequiredPropertyException("ForwardingArgs", "destinations");
            }
            if ($.source == null) {
                throw new MissingRequiredPropertyException("ForwardingArgs", "source");
            }
            return $;
        }
    }

}
