// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.email;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MailboxArgs extends com.pulumi.resources.ResourceArgs {

    public static final MailboxArgs Empty = new MailboxArgs();

    /**
     * Aliases for email
     * 
     */
    @Import(name="aliases")
    private @Nullable Output<List<String>> aliases;

    /**
     * @return Aliases for email
     * 
     */
    public Optional<Output<List<String>>> aliases() {
        return Optional.ofNullable(this.aliases);
    }

    /**
     * Domain name
     * 
     */
    @Import(name="domain", required=true)
    private Output<String> domain;

    /**
     * @return Domain name
     * 
     */
    public Output<String> domain() {
        return this.domain;
    }

    /**
     * Login
     * 
     */
    @Import(name="login", required=true)
    private Output<String> login;

    /**
     * @return Login
     * 
     */
    public Output<String> login() {
        return this.login;
    }

    /**
     * Mailbox type
     * 
     */
    @Import(name="mailboxType")
    private @Nullable Output<String> mailboxType;

    /**
     * @return Mailbox type
     * 
     */
    public Optional<Output<String>> mailboxType() {
        return Optional.ofNullable(this.mailboxType);
    }

    /**
     * Password
     * 
     */
    @Import(name="password", required=true)
    private Output<String> password;

    /**
     * @return Password
     * 
     */
    public Output<String> password() {
        return this.password;
    }

    private MailboxArgs() {}

    private MailboxArgs(MailboxArgs $) {
        this.aliases = $.aliases;
        this.domain = $.domain;
        this.login = $.login;
        this.mailboxType = $.mailboxType;
        this.password = $.password;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MailboxArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MailboxArgs $;

        public Builder() {
            $ = new MailboxArgs();
        }

        public Builder(MailboxArgs defaults) {
            $ = new MailboxArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param aliases Aliases for email
         * 
         * @return builder
         * 
         */
        public Builder aliases(@Nullable Output<List<String>> aliases) {
            $.aliases = aliases;
            return this;
        }

        /**
         * @param aliases Aliases for email
         * 
         * @return builder
         * 
         */
        public Builder aliases(List<String> aliases) {
            return aliases(Output.of(aliases));
        }

        /**
         * @param aliases Aliases for email
         * 
         * @return builder
         * 
         */
        public Builder aliases(String... aliases) {
            return aliases(List.of(aliases));
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain Domain name
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param login Login
         * 
         * @return builder
         * 
         */
        public Builder login(Output<String> login) {
            $.login = login;
            return this;
        }

        /**
         * @param login Login
         * 
         * @return builder
         * 
         */
        public Builder login(String login) {
            return login(Output.of(login));
        }

        /**
         * @param mailboxType Mailbox type
         * 
         * @return builder
         * 
         */
        public Builder mailboxType(@Nullable Output<String> mailboxType) {
            $.mailboxType = mailboxType;
            return this;
        }

        /**
         * @param mailboxType Mailbox type
         * 
         * @return builder
         * 
         */
        public Builder mailboxType(String mailboxType) {
            return mailboxType(Output.of(mailboxType));
        }

        /**
         * @param password Password
         * 
         * @return builder
         * 
         */
        public Builder password(Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        public MailboxArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("MailboxArgs", "domain");
            }
            if ($.login == null) {
                throw new MissingRequiredPropertyException("MailboxArgs", "login");
            }
            if ($.password == null) {
                throw new MissingRequiredPropertyException("MailboxArgs", "password");
            }
            return $;
        }
    }

}
