// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";
import * as domains from "./domains";
import * as email from "./email";
import * as livedns from "./livedns";
import * as simplehosting from "./simplehosting";
import * as types from "./types";

export {
    config,
    domains,
    email,
    livedns,
    simplehosting,
    types,
};
pulumi.runtime.registerResourcePackage("gandi", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:gandi") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
