// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.gandi.Utilities;
import com.pulumi.gandi.livedns.inputs.GetDomainArgs;
import com.pulumi.gandi.livedns.inputs.GetDomainNameserverArgs;
import com.pulumi.gandi.livedns.inputs.GetDomainNameserverPlainArgs;
import com.pulumi.gandi.livedns.inputs.GetDomainPlainArgs;
import com.pulumi.gandi.livedns.outputs.GetDomainNameserverResult;
import com.pulumi.gandi.livedns.outputs.GetDomainResult;
import java.util.concurrent.CompletableFuture;

public final class LivednsFunctions {
    public static Output<GetDomainResult> getDomain(GetDomainArgs args) {
        return getDomain(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDomainResult> getDomainPlain(GetDomainPlainArgs args) {
        return getDomainPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDomainResult> getDomain(GetDomainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("gandi:livedns/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDomainResult> getDomain(GetDomainArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("gandi:livedns/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDomainResult> getDomainPlain(GetDomainPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("gandi:livedns/getDomain:getDomain", TypeShape.of(GetDomainResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDomainNameserverResult> getDomainNameserver(GetDomainNameserverArgs args) {
        return getDomainNameserver(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDomainNameserverResult> getDomainNameserverPlain(GetDomainNameserverPlainArgs args) {
        return getDomainNameserverPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDomainNameserverResult> getDomainNameserver(GetDomainNameserverArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("gandi:livedns/getDomainNameserver:getDomainNameserver", TypeShape.of(GetDomainNameserverResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDomainNameserverResult> getDomainNameserver(GetDomainNameserverArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("gandi:livedns/getDomainNameserver:getDomainNameserver", TypeShape.of(GetDomainNameserverResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDomainNameserverResult> getDomainNameserverPlain(GetDomainNameserverPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("gandi:livedns/getDomainNameserver:getDomainNameserver", TypeShape.of(GetDomainNameserverResult.class), args, Utilities.withVersion(options));
    }
}
