// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gandi.livedns;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RecordArgs extends com.pulumi.resources.ResourceArgs {

    public static final RecordArgs Empty = new RecordArgs();

    @Import(name="mutable")
    private @Nullable Output<Boolean> mutable;

    public Optional<Output<Boolean>> mutable() {
        return Optional.ofNullable(this.mutable);
    }

    /**
     * The name of the record
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the record
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The TTL of the record
     * 
     */
    @Import(name="ttl", required=true)
    private Output<Integer> ttl;

    /**
     * @return The TTL of the record
     * 
     */
    public Output<Integer> ttl() {
        return this.ttl;
    }

    /**
     * The type of the record
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The type of the record
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * A list of values of the record
     * 
     */
    @Import(name="values", required=true)
    private Output<List<String>> values;

    /**
     * @return A list of values of the record
     * 
     */
    public Output<List<String>> values() {
        return this.values;
    }

    /**
     * The FQDN of the domain
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return The FQDN of the domain
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private RecordArgs() {}

    private RecordArgs(RecordArgs $) {
        this.mutable = $.mutable;
        this.name = $.name;
        this.ttl = $.ttl;
        this.type = $.type;
        this.values = $.values;
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RecordArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RecordArgs $;

        public Builder() {
            $ = new RecordArgs();
        }

        public Builder(RecordArgs defaults) {
            $ = new RecordArgs(Objects.requireNonNull(defaults));
        }

        public Builder mutable(@Nullable Output<Boolean> mutable) {
            $.mutable = mutable;
            return this;
        }

        public Builder mutable(Boolean mutable) {
            return mutable(Output.of(mutable));
        }

        /**
         * @param name The name of the record
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the record
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param ttl The TTL of the record
         * 
         * @return builder
         * 
         */
        public Builder ttl(Output<Integer> ttl) {
            $.ttl = ttl;
            return this;
        }

        /**
         * @param ttl The TTL of the record
         * 
         * @return builder
         * 
         */
        public Builder ttl(Integer ttl) {
            return ttl(Output.of(ttl));
        }

        /**
         * @param type The type of the record
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of the record
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param values A list of values of the record
         * 
         * @return builder
         * 
         */
        public Builder values(Output<List<String>> values) {
            $.values = values;
            return this;
        }

        /**
         * @param values A list of values of the record
         * 
         * @return builder
         * 
         */
        public Builder values(List<String> values) {
            return values(Output.of(values));
        }

        /**
         * @param values A list of values of the record
         * 
         * @return builder
         * 
         */
        public Builder values(String... values) {
            return values(List.of(values));
        }

        /**
         * @param zone The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The FQDN of the domain
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public RecordArgs build() {
            if ($.ttl == null) {
                throw new MissingRequiredPropertyException("RecordArgs", "ttl");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("RecordArgs", "type");
            }
            if ($.values == null) {
                throw new MissingRequiredPropertyException("RecordArgs", "values");
            }
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("RecordArgs", "zone");
            }
            return $;
        }
    }

}
